eureka:
  client:
    register-with-eureka: 'true'
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: 'true'
    appname: ${spring.application.name}
spring:
  application:
    name: users-ws
  devtools:
    restart:
      enabled: 'true'
  datasource:
    password: 'null'
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: 'true'
      settings:
        web-allow-others: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: ${PORT:8083}
